version: "3.7"
services:
  # db-mysql:
  #   image: mysql:5.7
  #   container_name: db-mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #   ports:
  #     - "3306:3306"
  db-psql:
    image: postgres:9
    container_name: db-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
